<script setup>
import {Head,router} from '@inertiajs/vue3';import AppLayout from '../Layouts/AppLayout.vue';import EmptyState from '../Components/EmptyState.vue';
defineProps({current:Object,standings:Array,captains:Array,ownership:Array,liveTable:Array,support:Array});
const refresh=()=>router.reload({only:['liveTable','support','standings','captains','ownership']});
</script>
<template><Head title="Live"/><AppLayout><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="label">{{current?.name||'Gameweek'}} command centre</p><h1 class="mt-2 text-4xl font-black">Live room.</h1><p class="mt-2 text-[#718078]">Provisional ranks, remaining players and every result that matters.</p></div><div class="flex items-center gap-3"><button @click="refresh" class="rounded-full border border-black/10 px-4 py-2 text-xs font-bold dark:border-white/10">↻ Refresh</button><span class="rounded-full bg-red-100 px-4 py-2 text-xs font-black uppercase tracking-widest text-red-600 dark:bg-red-950/40">● Live data</span></div></div>
<template v-if="liveTable.length"><section class="card mt-8 overflow-hidden"><div class="border-b border-black/5 p-6 dark:border-white/10"><div class="flex justify-between"><div><h2 class="text-xl font-black">Provisional league</h2><p class="text-sm text-[#718078]">Calculated from published picks and current player points</p></div><span class="label">Auto-syncs every 10 min</span></div></div><div class="overflow-x-auto"><table class="w-full min-w-190 text-left"><thead class="label"><tr><th class="px-6 py-4">Live</th><th>Manager</th><th class="text-right">GW</th><th class="text-right">Total</th><th class="text-right">To play</th><th class="px-6 text-right">Movement</th></tr></thead><tbody><tr v-for="r in liveTable" class="border-t border-black/5 dark:border-white/8"><td class="px-6 py-5 text-xl font-black">{{r.live_rank}}</td><td><b>{{r.manager}}</b><small class="block text-[#718078]">{{r.team}}</small></td><td class="text-right font-bold">{{r.gameweek_points}}</td><td class="text-right text-lg font-black">{{r.provisional_total}}</td><td class="text-right">{{r.remaining}}</td><td class="px-6 text-right font-bold" :class="r.movement>0?'text-emerald-600':r.movement<0?'text-red-500':'text-[#87958d]'">{{r.movement>0?`↑ ${r.movement}`:r.movement<0?`↓ ${Math.abs(r.movement)}`:'—'}}</td></tr></tbody></table></div></section>
<div class="mt-7 grid gap-6 lg:grid-cols-2"><section class="card p-6"><h2 class="text-xl font-black">Who are you supporting?</h2><p class="mt-1 text-sm text-[#718078]">A five-point return produces the indicated combined swing.</p><div class="mt-5 space-y-3"><div v-for="p in support" class="rounded-2xl bg-[#edf1ed] p-4 dark:bg-[#172a21]"><div class="flex justify-between"><div><b>{{p.name}}</b><span class="ml-2 text-xs text-[#718078]">{{p.points}} pts now</span></div><span class="rounded-full bg-white px-2 py-1 text-xs font-black text-[#1d6949] dark:bg-[#20382d]">+{{p.swing}} swing</span></div><p class="mt-2 text-xs text-[#718078]">Helps {{p.owners.join(', ')}}<template v-if="p.captainers.length"> · Captained by {{p.captainers.join(', ')}}</template></p></div></div></section><section class="card p-6"><h2 class="text-xl font-black">Captaincy battle</h2><div class="mt-6 space-y-5"><div v-for="c in captains"><div class="flex justify-between"><b>{{c.name}}</b><span>{{c.count}} captain{{c.count===1?'':'s'}}</span></div><div class="my-2 h-2 rounded-full bg-[#e4e9e5] dark:bg-[#20332a]"><div class="h-full rounded-full bg-[#f4d35e]" :style="{width:`${c.count/standings.length*100}%`}"></div></div><small class="text-[#718078]">{{c.managers.join(', ')}}</small></div></div></section></div>
<section class="mt-7"><h2 class="mb-4 text-xl font-black">Mini-league ownership</h2><div class="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6"><div v-for="o in ownership" class="card p-4"><b>{{o.name}}</b><span class="mt-2 block text-2xl font-black">{{o.percent}}%</span><small class="text-[#718078]">{{o.count}} of 6</small></div></div></section></template><EmptyState v-else class="mt-8" title="Waiting for live scoring" text="Run the FPL sync after picks are published. Provisional ranks and impact analysis will appear here."/></AppLayout></template>
