<script setup>
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { computed, ref, watch } from 'vue';
import AppLayout from '../../Layouts/AppLayout.vue'; import EmptyState from '../../Components/EmptyState.vue'; import PitchPlayer from '../../Components/PitchPlayer.vue';
const props=defineProps({entry:Object,current:Object,snapshot:Object,picks:Array,bank:Number,plans:Array,selectedPlan:Object,recommendations:Array,replacing:Object,availableEntries:Array});
const linkForm=useForm({fpl_entry_id:''}); const draft=ref((props.picks||[]).map(p=>({...p}))); const draftBank=ref(props.bank||0); const planName=ref(props.selectedPlan?.name||`GW${props.current?.number||1} plan`); const freeTransfers=ref(props.selectedPlan?.free_transfers??1); const changed=ref(false);
watch(()=>props.picks,v=>{draft.value=(v||[]).map(p=>({...p}));draftBank.value=props.bank||0;changed.value=false});
const starters=computed(()=>draft.value.slice(0,11)); const bench=computed(()=>draft.value.slice(11));
const line=(role)=>starters.value.filter(p=>p.element_type===role);
const chooseReplace=(p)=>router.get('/team-lab',{replace:p.id,plan:props.selectedPlan?.id},{preserveScroll:true});
const apply=(candidate)=>{const i=draft.value.findIndex(p=>p.id===props.replacing.id);if(i<0)return;const old=draft.value[i];draft.value[i]={...candidate,position:old.position,multiplier:old.multiplier,is_captain:old.is_captain,is_vice_captain:old.is_vice_captain,element:candidate.id};draftBank.value+=old.price-candidate.price;changed.value=true;router.get('/team-lab',{plan:props.selectedPlan?.id??0},{preserveScroll:true,preserveState:true});};
const save=(copy=false)=>useForm({id:copy?null:props.selectedPlan?.id,name:planName.value,squad:draft.value.map(p=>p.id),bank:draftBank.value,free_transfers:freeTransfers.value}).post('/team-lab/plans');
</script>
<template><Head title="Team Lab"/><AppLayout>
 <div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="label">Private planning room</p><h1 class="mt-2 text-4xl font-black tracking-tight">Team Lab.</h1><p class="mt-2 text-[#718078]">Inspect the squad, test transfers and keep the next move private.</p></div><div v-if="entry" class="card flex items-center gap-4 px-5 py-3"><div><span class="label block">Linked team</span><b>{{entry.team_name}}</b></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Private</span></div></div>
 <section v-if="!entry" class="card mx-auto max-w-xl p-7 sm:p-9"><span class="label">One-time setup</span><h2 class="mt-2 text-2xl font-black">Link your Mandem team</h2><p class="mt-2 text-sm leading-6 text-[#718078]">Choose your manager. A league entry can only be claimed by one account.</p><form @submit.prevent="linkForm.post('/team-lab/link')" class="mt-6"><select v-model="linkForm.fpl_entry_id" class="field"><option value="" disabled>Select your team</option><option v-for="e in availableEntries" :value="e.id">{{e.manager_name}} · {{e.team_name}}</option></select><p v-if="linkForm.errors.fpl_entry_id" class="mt-2 text-sm text-red-500">{{linkForm.errors.fpl_entry_id}}</p><button class="btn-primary mt-4 w-full">Link my team →</button></form></section>
 <EmptyState v-else-if="!picks?.length" title="Squad data is not available yet" text="Run php artisan fpl:sync after the gameweek deadline to import the latest published picks."/>
 <template v-else><div class="grid gap-7 xl:grid-cols-[1.45fr_.9fr]">
   <div><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><span class="label">{{current?.name}} squad</span><b class="ml-3 text-sm">Bank £{{(draftBank/10).toFixed(1)}}m</b></div><select v-if="plans.length" :value="selectedPlan?.id??0" @change="router.get('/team-lab',{plan:$event.target.value})" class="field !w-auto !py-2 text-sm"><option :value="0">Current squad</option><option v-for="p in plans" :value="p.id">{{p.name}}</option></select></div>
   <div class="overflow-hidden rounded-3xl border-4 border-white/70 bg-[#237a4b] shadow-xl dark:border-[#20342b]"><div class="relative min-h-185 bg-[linear-gradient(rgba(255,255,255,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.09)_1px,transparent_1px)] bg-[size:48px_48px] p-5 sm:p-8"><div class="pointer-events-none absolute inset-x-0 top-1/2 border-t-2 border-white/30"></div><div class="pointer-events-none absolute left-1/2 top-1/2 size-28 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white/30"></div>
    <div class="relative flex min-h-148 flex-col justify-between py-2"><div class="flex justify-center"><PitchPlayer v-for="p in line(1)" :key="p.id" :player="p" planning @replace="chooseReplace"/></div><div class="flex justify-around"><PitchPlayer v-for="p in line(2)" :key="p.id" :player="p" planning @replace="chooseReplace"/></div><div class="flex justify-around"><PitchPlayer v-for="p in line(3)" :key="p.id" :player="p" planning @replace="chooseReplace"/></div><div class="flex justify-around"><PitchPlayer v-for="p in line(4)" :key="p.id" :player="p" planning @replace="chooseReplace"/></div></div></div>
    <div class="border-t border-white/20 bg-[#165f39] p-5"><span class="label !text-white/60">Bench</span><div class="mt-4 flex justify-around"><PitchPlayer v-for="p in bench" :key="p.id" :player="p" planning @replace="chooseReplace"/></div></div></div>
  </div>
  <aside class="space-y-5"><section v-if="replacing" class="card p-6"><div class="flex justify-between"><div><span class="label">Replacement finder</span><h2 class="mt-2 text-2xl font-black">Sell {{replacing.name}}?</h2><p class="text-sm text-[#718078]">Budget: £{{((replacing.price+draftBank)/10).toFixed(1)}}m</p></div><Link href="/team-lab" class="text-[#718078]">×</Link></div><div class="mt-5 space-y-3"><article v-for="r in recommendations" class="rounded-2xl border border-black/7 p-4 dark:border-white/10"><div class="flex items-start justify-between"><div><Link :href="`/players/${r.id}`" class="font-black hover:text-emerald-600">{{r.name}}</Link><p class="text-xs text-[#718078]">{{r.team}} · £{{(r.price/10).toFixed(1)}}m · {{r.form}} form</p></div><span class="rounded-full bg-[#e3eee6] px-2 py-1 text-xs font-black text-[#1c6b49] dark:bg-[#173226]">{{r.score}}</span></div><ul class="mt-3 space-y-1 text-xs text-[#617169]"><li v-for="reason in r.reasons">✓ {{reason}}</li></ul><div class="mt-3 flex gap-1"><span v-for="f in r.fixtures" class="rounded-md px-1.5 py-1 text-[9px] font-bold" :class="f.difficulty<=2?'bg-emerald-100 text-emerald-700':f.difficulty>=4?'bg-red-100 text-red-700':'bg-slate-100 text-slate-700'">{{f.opponent}} {{f.venue}}</span></div><button @click="apply(r)" class="btn-primary mt-4 w-full !py-2 text-xs">Add to draft</button></article><p v-if="!recommendations.length" class="text-sm text-[#718078]">No valid replacements within budget.</p></div></section>
   <section v-else class="card p-6"><span class="label">How it works</span><h2 class="mt-2 text-xl font-black">Build without regret.</h2><ol class="mt-5 space-y-4 text-sm text-[#617169]"><li><b class="mr-2 text-[#173f2e] dark:text-[#f4d35e]">01</b> Hover or tap a player and choose Replace.</li><li><b class="mr-2 text-[#173f2e] dark:text-[#f4d35e]">02</b> Compare form, fixtures and recommendation score.</li><li><b class="mr-2 text-[#173f2e] dark:text-[#f4d35e]">03</b> Apply the move and save the draft.</li></ol></section>
   <section class="card p-6"><span class="label">Saved transfer plan</span><input v-model="planName" class="field mt-3" placeholder="Plan name"><div class="mt-3 grid grid-cols-2 gap-3"><label><span class="label">Bank</span><div class="field mt-1 !py-2">£{{(draftBank/10).toFixed(1)}}m</div></label><label><span class="label">Free transfers</span><select v-model="freeTransfers" class="field mt-1 !py-2"><option v-for="n in 6" :value="n-1">{{n-1}}</option></select></label></div><button @click="save(false)" class="btn-primary mt-4 w-full">{{selectedPlan?'Update plan':'Save plan'}}</button><button v-if="selectedPlan" @click="save(true)" class="mt-2 w-full py-2 text-xs font-bold text-[#64746b]">Save as a new plan</button><p v-if="changed" class="mt-3 text-center text-xs text-amber-600">Unsaved changes</p></section>
  </aside></div></template>
</AppLayout></template>
